package domain;

import java.io.Serializable;

public class Employee implements Serializable {

    private String id;
    private String name;
    private int ticketsProcessed;
    private double revenueGenerated;

    /**
    * Creates an employee with basic identification information and initializes performance statistics.
    */

    public Employee(String id, String name) {
        this.id = id;
        this.name = name;
        this.ticketsProcessed = 0;
        this.revenueGenerated = 0;
    }

    /**
    * Returns the unique identifier of the employee.
    */

    public String getId() {
        return id;
    }

    /**
    * Returns the name of the employee.
    */

    public String getName() {
        return name;
    }

    /**
    * Increases the number of tickets processed by the employee.
    */

    public void registerTicket() {
        ticketsProcessed++;
    }

    /**
    * Adds the specified amount to the revenue generated by the employee.
    */

    public void addRevenue(double amount) {
        revenueGenerated += amount;
    }

    /**
    * Returns the total number of tickets processed by the employee.
    */

    public int getTicketsProcessed() {
        return ticketsProcessed;
    }

    /**
    * Returns the total revenue generated by the employee.
    */

    public double getRevenueGenerated() {
        return revenueGenerated;
    }

    /**
    * Calculates and returns the average revenue generated per processed ticket.
    */

    public double getAverageRevenuePerTicket() {

        if (ticketsProcessed == 0) {
            return 0;
        }

        return revenueGenerated / ticketsProcessed;
    }

    /**
     * Determines and returns the employee's performance level based on their work statistics.
    */

    public String getPerformanceLevel() {

        if (ticketsProcessed >= 50) {
            return "Excellent";
        }

        if (ticketsProcessed >= 20) {
            return "Good";
        }

        return "Needs Improvement";
    }      
}